#!/bin/bash

COUNTER=0
while [  $COUNTER -lt $1 ]; do
    echo The counter is $COUNTER
    echo $2/sol_${COUNTER}.dat
    ../../../bin/oomph-convert.py $2/soln${COUNTER}.dat $2/soln_$COUNTER.vtu
    let COUNTER=COUNTER+1 
done
