#!/bin/bash

if [ -d RESLT ]; then
    echo RESLT directory exists
else
    mkdir RESLT
fi

./spherical_solid_w_contact_static --enfvol 1 --maxnsteps 150 --nreler $2 --program standard0.05Steps --newtontol $3 --lambda \
$4 --tshell $5 --C1 $6 --C2 $7

tar -zcf RESLT_Run${1}_nreler=${2}_nt=${3}_lambda=${4}_tshell=${5}_C1=${6}_C2=${7}.tar.gz RESLT
