#!/bin/bash          

if [ -d RESLT ]; then
    echo RESLT directory exists
else
    mkdir RESLT
fi 

./spherical_solid_w_contact --enfvol 1 --maxnsteps 150 --nreler $2 --program lowerHto0.99 --newtontol $3 --lambda $4 --tshell $5 --C1 $6 --C2 $7

tar -zcf RESLT_$1.tar.gz RESLT 
